### ISSUE TITLE
Documentation for classes `NeuronSimTree` and `NeuronCompartmentTree` not rendering

### ISSUE THREAD

**Issue by WillemWybo** [unibe-cns/NEAT#112]
`NeuronSimTree` [documentation](https://neatdend.readthedocs.io/en/latest/reference/trees.html#simulate-neuron-models) and `NeuronCompartmentTree` [documentation](https://neatdend.readthedocs.io/en/latest/reference/trees.html#simulate-reduced-compartmental-models) does not render correctly. Tried a fake `h` import in `neuronmodel.py` but it does not help.

**Comment by benelot** [comment]
Ok, the problem for `NeuronCompartmentTree` is visible right here: https://neatdend.readthedocs.io/en/latest/reference/trees.html#simulate-neuron-models

**Comment by benelot** [comment]
You were close to the solution if the import of the classes were correct. both are in neat.tools.neuron.neuronmodel not neat.tools.neuron. If you want them to be importable by only the neuron module, then we should add them to the __init__.py. Do you want to do that, @WillemWybo?

Your fakeh was close to the other part of the solution, but it the object also needed to be iterable. I included the universal, iterable mock object. It is basically a thing that never does anything, but you can do with it what you want. For any method except the ones for the iterator, it just returns another instance of itself. Neat, right?

**Comment by benelot** [comment]
Weeell, it took some more tricks to make it as far as it is now. But there is a bigger problem it seems. Now that I could properly make the NeuronSimTree get documented, the bac_firing example does not work anymore. It seems you are using there a NeuronSimTree, which can be considered entirely disfunctional as it contains Neuron code that is entirely mocked. How is that supposed to work? Why did it work in the first place? I am a bit confused.

@WillemWybo Can you test what is going on in the bac_firing example if there is no neuron installed? I do not understand enough to understand the example. Just add some raise Exception() before the try import neuron part in the neuronmodel.py file and see what happens if you run the bac_firing.py example. Here I get some problem which says that the self.root.e_eq is not a 1-dimensional array and thus can not be turned into a float.

**Comment by benelot** [comment]
Hmm, the examples still seem to be there. I am even more confused. I commented the whole section in the conf.py
```
#sphinx_gallery_conf = {
#    'examples_dirs': '../examples',   # path to your example scripts
#    'gallery_dirs': 'auto_examples',  # path to where to save gallery generated output
#    'filename_pattern': '/',
#    'ignore_pattern': r'.*util\.py'
#}
```

**Comment by WillemWybo** [comment]
Ha I think I see the issue. When neuron is not installed, the example scripts don't actually run anything, they just plot a stored image (or at least, that's what should happen). In that way, the stored image shows up on the webpage. To do so, they tried to import the `NEURON` components and if that fails a `SIM_FLAG` is switched of
```

SIM_FLAG = 1
try:
    from neat import NeuronSimTree, NeuronCompartmentTree, createReducedNeuronModel
except ImportError:
    warnings.warn('NEURON not available, plotting stored image', UserWarning)
    SIM_FLAG = 0
```
However, because we now have a fake module, no `ImportError` is raised and the simulations fail to run (since there is no real `NEURON`).

**Comment by benelot** [comment]
Ah right. Ok, then I was just too exhausted to figure this out :D Thanks for giving me that hint. That sounds like something we can actually fix again.

**Comment by benelot** [comment]
Easy fix by adding `import neuron` to the try except in the examples. Some had it already. Now everything should be working as expected.
